version: '3'
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    ports:
      - "8080:8080"
    volumes:
      - /data/work/FreshRSS/data:/var/www/FreshRSS/data
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    restart: always