version: '3'
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    ports:
      - "8080:3080"
    volumes:
      - ./data:/var/www/FreshRSS/data
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    restart: always